export const termsOfService = [
  "Last updated: September 14, 2026. These Terms of Service govern your use of Mr Wallpapers and mrwallpaper.org, including the installable web-app experience. By using the service, you agree to these terms. If you do not agree, do not use the service.",
  "Service description. Mr Wallpapers provides access to wallpapers and related browsing, search, personalization, account, favorites, download, and installed web-app features. The current website is offered as a free service. We may add, remove, improve, or discontinue features over time.",
  "Accounts. You are responsible for the accuracy of information associated with your account and for keeping your credentials secure. You may use supported sign-in methods such as email/password or Google sign-in. You may not impersonate others or use the service for fraudulent or unlawful activity.",
  "Personalization. Recommendations, For You results, sorting, and other content suggestions may use saved preferences, category interests, favorites, or service activity. Personalized results are provided for convenience and may change over time; we do not guarantee that recommendations will always match your interests.",
  "Acceptable use. You may not interfere with the service, attempt unauthorized access, abuse automated systems, bypass security controls, scrape or mirror the service at unreasonable scale, upload malicious content, or use Mr Wallpapers in a way that violates applicable law or the rights of others.",
  "Wallpaper use and intellectual property. Wallpapers may be owned by Mr Wallpapers, contributing creators, licensors, or other rights holders. Unless a specific wallpaper or rights holder states otherwise, downloads are provided for personal device-background use only. Downloading a wallpaper does not transfer ownership or give you permission to resell, redistribute, sublicense, mirror, falsely claim authorship of, or commercially exploit the wallpaper. You are responsible for ensuring your use complies with applicable rights and laws.",
  "Installed web app and updates. Mr Wallpapers may be installed as a Progressive Web App and may cache parts of the service on your device. Cached pages or static assets can occasionally be older than the latest version until the app refreshes or updates. We may change the app shell, caching behavior, or supported installation features as the service evolves.",
  "Copyright complaints. If you believe content on Mr Wallpapers infringes your rights, use the available reporting process or contact us with enough information to identify the copyrighted work, the allegedly infringing material and its URL, your contact information, and the basis of your claim. We may remove or restrict content while reviewing a complaint.",
  "Availability. We aim to keep Mr Wallpapers available and reliable, but we do not guarantee uninterrupted, error-free, or permanent access. Maintenance, provider outages, abuse prevention, technical issues, cached versions, or other events may temporarily affect the service.",
  "Third-party services. Mr Wallpapers relies on third-party providers, including services for hosting, storage, authentication, databases, DNS/CDN, analytics where configured, and email delivery. Your use of certain features may also be subject to those providers' applicable terms and policies.",
  "Suspension and termination. We may restrict or terminate access when reasonably necessary to protect the service or users, respond to legal requirements, address security risks, or stop abuse or violations of these terms.",
  "Disclaimers. Mr Wallpapers is provided on an 'as is' and 'as available' basis to the extent permitted by law. We do not guarantee that every wallpaper is suitable for every device, purpose, or jurisdiction, that recommendations will always be accurate, or that all metadata and content will always be complete or error-free.",
  "Limitation of liability. To the maximum extent permitted by applicable law, Mr Wallpapers and its operators will not be liable for indirect, incidental, special, consequential, or punitive damages arising from use of or inability to use the service. Nothing in these terms excludes liability that cannot legally be excluded.",
  "Changes to these terms. We may update these Terms of Service as the service changes. Continued use of Mr Wallpapers after updated terms are posted means you accept the revised terms to the extent permitted by law.",
];

export const copyrightPolicy = [
  "Only content that may lawfully be distributed should be published on Mr Wallpapers. Content may be removed or restricted when we receive a credible infringement complaint or otherwise become aware of a rights issue.",
  "To report infringement, use Report on a wallpaper where available or contact us through the site. Please identify the copyrighted work, provide the exact Mr Wallpapers URL or other information sufficient to locate the material, provide your contact information, explain the basis of your claim, and state that you have a good-faith belief the disputed use is not authorized by the rights holder, its agent, or applicable law.",
  "Your complaint should also state that the information you provide is accurate and that you are the rights holder or are authorized to act on the rights holder's behalf. Including your physical or electronic signature helps us verify and process the request.",
  "We may remove or restrict content while a complaint is reviewed and may take action against accounts or contributors associated with repeated infringement. Where appropriate, we may ask for additional information before acting.",
  "Knowingly submitting false or misleading copyright claims may have legal consequences. This page provides general process information and is not legal advice.",
];
