export const termsOfService = [
  "Last updated: September 18, 2026. These Terms of Service govern your use of Mr Wallpapers and mrwallpaper.org, including the installable web-app experience. By using the service, you agree to these terms. If you do not agree, do not use the service.",
  "Service description. Mr Wallpapers provides free wallpapers and related browsing, search, personalization, account, favorites, download, community-submission, and installed web-app features. The website is offered as a free service. We may add, remove, improve, or discontinue features over time.",
  "Accounts. An account is not required to download ordinary free wallpapers. Some features, including favorites, saved activity, notifications, and wallpaper submissions, may require an account. You are responsible for the accuracy of information associated with your account and for keeping your credentials secure.",
  "Community wallpaper submissions. Signed-in users may submit wallpapers for review. By submitting content, you confirm that you created it or otherwise have the rights and permissions needed to let Mr Wallpapers store, review, display, reproduce, make available for download, and distribute it as a free wallpaper. You retain any ownership you already have; submitting does not transfer copyright ownership to Mr Wallpapers.",
  "License for approved submissions. For content you submit, you grant Mr Wallpapers a non-exclusive, worldwide, royalty-free license to host, store, process, resize, create previews and thumbnails from, display, promote, and distribute the submitted content through Mr Wallpapers for as long as it remains part of the service. You may contact us to request removal, subject to reasonable technical, legal, and backup-retention requirements.",
  "Submission review. Community submissions are not published automatically. Mr Wallpapers may approve, reject, remove, or request changes to a submission based on quality, duplication, safety, rights concerns, metadata accuracy, or service needs. Submission does not guarantee publication, attribution, payment, compensation, or continued availability.",
  "AI-assisted metadata. Submitters may optionally use an AI-assisted metadata feature to generate a title, description, tags, alt text, primary keyword, or category suggestion from an uploaded wallpaper preview. AI-generated suggestions can be inaccurate. Submitters should review and correct the metadata before submitting, and Mr Wallpapers may edit metadata during moderation.",
  "Personalization. Recommendations, sorting, and other content suggestions may use saved preferences, category interests, favorites, or service activity. Personalized results are provided for convenience and may change over time.",
  "Acceptable use. You may not interfere with the service, attempt unauthorized access, abuse automated systems, bypass security controls, upload malicious content, submit content you do not have the right to distribute, or use Mr Wallpapers in a way that violates applicable law or the rights of others.",
  "Wallpaper use and intellectual property. Wallpapers may be owned by Mr Wallpapers, community contributors, licensors, or other rights holders. Unless a specific wallpaper or rights holder states otherwise, downloads are provided for personal device-background use only. Downloading a wallpaper does not transfer ownership or give permission to resell, redistribute, sublicense, mirror, falsely claim authorship of, or commercially exploit it.",
  "Installed web app and updates. Mr Wallpapers may be installed as a Progressive Web App and may cache parts of the service on your device. Cached pages or static assets can occasionally be older than the latest version until the app refreshes or updates.",
  "Copyright complaints. If you believe content on Mr Wallpapers infringes your rights, use the available reporting process or contact us with enough information to identify the copyrighted work, the allegedly infringing material and its URL, your contact information, and the basis of your claim. We may remove or restrict content while reviewing a complaint.",
  "Availability. We aim to keep Mr Wallpapers available and reliable, but we do not guarantee uninterrupted, error-free, or permanent access. Maintenance, provider outages, abuse prevention, technical issues, cached versions, or other events may temporarily affect the service.",
  "Third-party services. Mr Wallpapers relies on third-party providers for hosting, storage, authentication, databases, DNS/CDN, analytics where configured, transactional email, and optional AI-assisted metadata generation. Those providers process information as needed to provide their services and are subject to their own terms and policies.",
  "Suspension and termination. We may restrict or terminate access when reasonably necessary to protect the service or users, respond to legal requirements, address security or copyright risks, or stop abuse or violations of these terms.",
  "Disclaimers. Mr Wallpapers is provided on an 'as is' and 'as available' basis to the extent permitted by law. We do not guarantee that every wallpaper is suitable for every device, purpose, or jurisdiction, or that all recommendations, AI-generated metadata, and content will always be complete or error-free.",
  "Limitation of liability. To the maximum extent permitted by applicable law, Mr Wallpapers and its operators will not be liable for indirect, incidental, special, consequential, or punitive damages arising from use of or inability to use the service. Nothing in these terms excludes liability that cannot legally be excluded.",
  "Changes to these terms. We may update these Terms of Service as the service changes. Continued use of Mr Wallpapers after updated terms are posted means you accept the revised terms to the extent permitted by law.",
];

export const copyrightPolicy = [
  "Only content that may lawfully be distributed should be published on Mr Wallpapers. Existing catalog wallpapers are uploaded and managed by Mr Wallpapers, while community submissions are reviewed before publication. A submission being approved does not guarantee that it is free of third-party rights.",
  "Community submitters must confirm that they created the submitted image or have permission to share and distribute it. Mr Wallpapers may reject, remove, restrict, or investigate content when ownership or permission is unclear, when a credible complaint is received, or when we otherwise become aware of a rights issue.",
  "To report infringement, use Report on a wallpaper where available or contact us through the site. Identify the copyrighted work, provide the exact Mr Wallpapers URL or enough information to locate the material, provide your contact information, explain the basis of your claim, and state that you have a good-faith belief the disputed use is not authorized by the rights holder, its agent, or applicable law.",
  "Your complaint should also state that the information you provide is accurate and that you are the rights holder or are authorized to act on the rights holder's behalf. Including your physical or electronic signature helps us verify and process the request.",
  "We may remove or restrict content while a complaint is reviewed and may take action against accounts associated with repeated infringement. Where appropriate, we may ask for additional information before acting.",
  "Knowingly submitting false or misleading copyright claims may have legal consequences. This page provides general process information and is not legal advice.",
];
