-- Seed catalog (idempotent)
insert into categories (id, slug, name, description, cover_url, sort_order, is_visible, is_featured)
values
('cat-minimal', 'minimal', 'Minimal', 'Quiet forms. Room to breathe.', '/wallpapers/quiet-orbit.jpg', 1, true, true),
('cat-aesthetic', 'aesthetic', 'Aesthetic', 'Soft grain and still color.', '/wallpapers/paper-moon.jpg', 2, true, true),
('cat-nature', 'nature', 'Nature', 'Ridges, water, dusk.', '/wallpapers/ridge-line.jpg', 3, true, true),
('cat-cars', 'cars', 'Cars', 'Roads, glow, night runs.', '/wallpapers/afterglow-run.jpg', 4, true, false),
('cat-anime', 'anime', 'Anime', 'Sky palettes, never characters.', '/wallpapers/after-rain-sky.jpg', 5, true, true),
('cat-space', 'space', 'Space', 'Moons, dust, distance.', '/wallpapers/silent-satellite.jpg', 6, true, true),
('cat-dark', 'dark', 'Dark', 'Low light. Deep grey.', '/wallpapers/low-light.jpg', 7, true, false),
('cat-abstract', 'abstract', 'Abstract', 'Shape, overlap, grid.', '/wallpapers/overlap-two.jpg', 8, true, false),
('cat-motivational', 'motivational', 'Motivational', 'Short lines. No noise.', '/wallpapers/begin-again.jpg', 9, true, false),
('cat-bible-verses', 'bible-verses', 'Bible Verses', 'Quiet scripture, set with care.', '/wallpapers/be-still.jpg', 10, true, true),
('cat-love', 'love', 'Love', 'Two marks. Warm dusk.', '/wallpapers/two-points.jpg', 11, true, false),
('cat-city', 'city', 'City', 'Windows, harbours, blue hour.', '/wallpapers/late-grid.jpg', 12, true, false),
('cat-animals', 'animals', 'Animals', 'Silhouette and scale.', '/wallpapers/crane-hour.jpg', 13, true, false),
('cat-vintage', 'vintage', 'Vintage', 'Paper, sepia, age.', '/wallpapers/sepia-room.jpg', 14, true, false),
('cat-amoled', 'amoled', 'AMOLED', 'True black. Hairline light.', '/wallpapers/true-black.jpg', 15, true, true),
('cat-iphone', 'iphone', 'iPhone', 'Composed for a tall screen.', '/wallpapers/soft-lock.jpg', 16, true, true)
on conflict (id) do nothing;

insert into tags (id, slug, name)
values
('tag-minimal', 'minimal', 'minimal'),
('tag-circle', 'circle', 'circle'),
('tag-calm', 'calm', 'calm'),
('tag-line', 'line', 'line'),
('tag-aesthetic', 'aesthetic', 'aesthetic'),
('tag-moon', 'moon', 'moon'),
('tag-film', 'film', 'film'),
('tag-grain', 'grain', 'grain'),
('tag-rose', 'rose', 'rose'),
('tag-nature', 'nature', 'nature'),
('tag-mountains', 'mountains', 'mountains'),
('tag-dusk', 'dusk', 'dusk'),
('tag-water', 'water', 'water'),
('tag-cars', 'cars', 'cars'),
('tag-road', 'road', 'road'),
('tag-sunset', 'sunset', 'sunset'),
('tag-night', 'night', 'night'),
('tag-bokeh', 'bokeh', 'bokeh'),
('tag-anime', 'anime', 'anime'),
('tag-sky', 'sky', 'sky'),
('tag-evening', 'evening', 'evening'),
('tag-space', 'space', 'space'),
('tag-stars', 'stars', 'stars'),
('tag-nebula', 'nebula', 'nebula'),
('tag-dark', 'dark', 'dark'),
('tag-black', 'black', 'black'),
('tag-seam', 'seam', 'seam'),
('tag-grey', 'grey', 'grey'),
('tag-abstract', 'abstract', 'abstract'),
('tag-grid', 'grid', 'grid'),
('tag-type', 'type', 'type'),
('tag-verse', 'verse', 'verse'),
('tag-psalm', 'psalm', 'psalm'),
('tag-genesis', 'genesis', 'genesis'),
('tag-love', 'love', 'love'),
('tag-city', 'city', 'city'),
('tag-blue hour', 'blue hour', 'blue hour'),
('tag-animals', 'animals', 'animals'),
('tag-bird', 'bird', 'bird'),
('tag-ocean', 'ocean', 'ocean'),
('tag-vintage', 'vintage', 'vintage'),
('tag-sepia', 'sepia', 'sepia'),
('tag-paper', 'paper', 'paper'),
('tag-amoled', 'amoled', 'amoled'),
('tag-geometry', 'geometry', 'geometry'),
('tag-iphone', 'iphone', 'iphone'),
('tag-lockscreen', 'lockscreen', 'lockscreen'),
('tag-dune', 'dune', 'dune')
on conflict (id) do nothing;

insert into wallpapers (id, title, description, category_id, access_type, status, width, height, file_size_bytes, format, aspect_ratio, download_count, favorite_count, published_at)
values
('quiet-orbit', 'Quiet Orbit', 'A single pale ring on warm ink.', 'cat-minimal', 'free', 'approved', 1080, 1920, 49320, 'jpg', '9:16', 18420, 2104, now() - interval '64 days'),
('one-line', 'One Line', 'A single horizon. Nothing else.', 'cat-minimal', 'free', 'approved', 1080, 1920, 48960, 'jpg', '9:16', 12110, 980, now() - interval '62 days'),
('paper-moon', 'Paper Moon', 'Soft disc on grainy cream.', 'cat-aesthetic', 'free', 'approved', 1080, 1920, 49200, 'jpg', '9:16', 22190, 3402, now() - interval '60 days'),
('film-dust', 'Film Dust', 'Muted rose field with grain.', 'cat-aesthetic', 'premium', 'approved', 1080, 1920, 49080, 'jpg', '9:16', 9800, 1502, now() - interval '58 days'),
('ridge-line', 'Ridge Line', 'Layered dusk mountains.', 'cat-nature', 'free', 'approved', 1080, 1920, 49200, 'jpg', '9:16', 41200, 6201, now() - interval '56 days'),
('still-water', 'Still Water', 'A lake held between two tones.', 'cat-nature', 'free', 'approved', 1080, 1920, 49320, 'jpg', '9:16', 19880, 2400, now() - interval '54 days'),
('afterglow-run', 'Afterglow Run', 'A road and a dying sun.', 'cat-cars', 'free', 'approved', 1080, 1920, 49560, 'jpg', '9:16', 16770, 1890, now() - interval '52 days'),
('night-circuit', 'Night Circuit', 'Taillight bokeh on asphalt.', 'cat-cars', 'premium', 'approved', 1080, 1920, 49560, 'jpg', '9:16', 13440, 2201, now() - interval '50 days'),
('after-rain-sky', 'After Rain Sky', 'Anime-influenced dusk, no characters.', 'cat-anime', 'free', 'approved', 1080, 1920, 49680, 'jpg', '9:16', 38820, 7102, now() - interval '48 days'),
('school-route', 'School Route', 'A quiet gradient evening.', 'cat-anime', 'premium', 'approved', 1080, 1920, 49440, 'jpg', '9:16', 15400, 2600, now() - interval '46 days'),
('silent-satellite', 'Silent Satellite', 'A pale moon over deep space.', 'cat-space', 'free', 'approved', 1080, 1920, 49920, 'jpg', '9:16', 27500, 4100, now() - interval '44 days'),
('kepler-dust', 'Kepler Dust', 'A distant band of light.', 'cat-space', 'premium', 'approved', 1080, 1920, 49320, 'jpg', '9:16', 11200, 1904, now() - interval '42 days'),
('low-light', 'Low Light', 'Near-black with a faint seam.', 'cat-dark', 'free', 'approved', 1080, 1920, 49080, 'jpg', '9:16', 30110, 4400, now() - interval '40 days'),
('charcoal-fold', 'Charcoal Fold', 'Soft planes of dark grey.', 'cat-dark', 'free', 'approved', 1080, 1920, 49560, 'jpg', '9:16', 9900, 870, now() - interval '38 days'),
('overlap-two', 'Overlap Two', 'Two translucent discs.', 'cat-abstract', 'free', 'approved', 1080, 1920, 49320, 'jpg', '9:16', 17600, 2055, now() - interval '36 days'),
('lattice-soft', 'Lattice Soft', 'A quiet geometric grid.', 'cat-abstract', 'premium', 'approved', 1080, 1920, 49440, 'jpg', '9:16', 6400, 720, now() - interval '34 days'),
('begin-again', 'Begin Again', 'A short line for a new morning.', 'cat-motivational', 'free', 'approved', 1080, 1920, 49320, 'jpg', '9:16', 25400, 3800, now() - interval '32 days'),
('make-room', 'Make Room', 'Space to think.', 'cat-motivational', 'premium', 'approved', 1080, 1920, 49080, 'jpg', '9:16', 8100, 1400, now() - interval '30 days'),
('be-still', 'Be Still', 'Psalm 46:10, set quietly.', 'cat-bible-verses', 'free', 'approved', 1080, 1920, 48960, 'jpg', '9:16', 19800, 2900, now() - interval '28 days'),
('let-there-be-light', 'Let There Be Light', 'Genesis 1:3.', 'cat-bible-verses', 'free', 'approved', 1080, 1920, 50160, 'jpg', '9:16', 22100, 3104, now() - interval '26 days'),
('two-points', 'Two Points', 'A pair of marks, close.', 'cat-love', 'free', 'approved', 1080, 1920, 49200, 'jpg', '9:16', 14300, 2600, now() - interval '24 days'),
('held', 'Held', 'Warm dusk, two tones.', 'cat-love', 'premium', 'approved', 1080, 1920, 48480, 'jpg', '9:16', 7700, 1500, now() - interval '22 days'),
('late-grid', 'Late Grid', 'A city as a set of windows.', 'cat-city', 'free', 'approved', 1080, 1920, 49080, 'jpg', '9:16', 26700, 3300, now() - interval '20 days'),
('harbour-hour', 'Harbour Hour', 'Blue hour over a skyline.', 'cat-city', 'premium', 'approved', 1080, 1920, 49440, 'jpg', '9:16', 10200, 1600, now() - interval '18 days'),
('crane-hour', 'Crane Hour', 'A single bird, a lot of sky.', 'cat-animals', 'free', 'approved', 1080, 1920, 49200, 'jpg', '9:16', 15900, 2100, now() - interval '16 days'),
('deep-hold', 'Deep Hold', 'A whale-scale curve.', 'cat-animals', 'premium', 'approved', 1080, 1920, 49080, 'jpg', '9:16', 8800, 1700, now() - interval '14 days'),
('sepia-room', 'Sepia Room', 'Warm vintage field.', 'cat-vintage', 'free', 'approved', 1080, 1920, 49200, 'jpg', '9:16', 11400, 1200, now() - interval '12 days'),
('old-letter', 'Old Letter', 'Paper, age, quiet type.', 'cat-vintage', 'free', 'approved', 1080, 1920, 49200, 'jpg', '9:16', 7600, 900, now() - interval '10 days'),
('true-black', 'True Black', 'AMOLED. A single thin ring.', 'cat-amoled', 'free', 'approved', 1080, 1920, 49200, 'jpg', '9:16', 45200, 8100, now() - interval '8 days'),
('thin-cross', 'Thin Cross', 'Two hairlines on true black.', 'cat-amoled', 'premium', 'approved', 1080, 1920, 49200, 'jpg', '9:16', 18900, 3400, now() - interval '6 days'),
('soft-lock', 'Soft Lock', 'Made for a tall phone screen.', 'cat-iphone', 'free', 'approved', 1080, 1920, 49080, 'jpg', '9:16', 33100, 5200, now() - interval '4 days'),
('lock-dune', 'Lock Dune', 'A gentle dune for the home screen.', 'cat-iphone', 'premium', 'approved', 1080, 1920, 49080, 'jpg', '9:16', 14100, 2300, now() - interval '2 days')
on conflict (id) do nothing;

insert into wallpaper_assets (id, wallpaper_id, kind, bucket, path, width, height, bytes, mime, is_public)
values
('quiet-orbit-thumb', 'quiet-orbit', 'thumbnail', 'public', '/wallpapers/quiet-orbit.jpg', 400, 711, 12000, 'image/jpeg', true),
('quiet-orbit-prev', 'quiet-orbit', 'preview', 'public', '/wallpapers/quiet-orbit.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('quiet-orbit-orig', 'quiet-orbit', 'original', 'protected', '/wallpapers/quiet-orbit.jpg', 1080, 1920, 48000, 'image/jpeg', false),
('one-line-thumb', 'one-line', 'thumbnail', 'public', '/wallpapers/one-line.jpg', 400, 711, 12000, 'image/jpeg', true),
('one-line-prev', 'one-line', 'preview', 'public', '/wallpapers/one-line.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('one-line-orig', 'one-line', 'original', 'protected', '/wallpapers/one-line.jpg', 1080, 1920, 48000, 'image/jpeg', false),
('paper-moon-thumb', 'paper-moon', 'thumbnail', 'public', '/wallpapers/paper-moon.jpg', 400, 711, 12000, 'image/jpeg', true),
('paper-moon-prev', 'paper-moon', 'preview', 'public', '/wallpapers/paper-moon.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('paper-moon-orig', 'paper-moon', 'original', 'protected', '/wallpapers/paper-moon.jpg', 1080, 1920, 48000, 'image/jpeg', false),
('film-dust-thumb', 'film-dust', 'thumbnail', 'public', '/wallpapers/film-dust.jpg', 400, 711, 12000, 'image/jpeg', true),
('film-dust-prev', 'film-dust', 'preview', 'public', '/wallpapers/film-dust.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('film-dust-orig', 'film-dust', 'original', 'protected', '/wallpapers/film-dust.jpg', 1080, 1920, 48000, 'image/jpeg', false),
('ridge-line-thumb', 'ridge-line', 'thumbnail', 'public', '/wallpapers/ridge-line.jpg', 400, 711, 12000, 'image/jpeg', true),
('ridge-line-prev', 'ridge-line', 'preview', 'public', '/wallpapers/ridge-line.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('ridge-line-orig', 'ridge-line', 'original', 'protected', '/wallpapers/ridge-line.jpg', 1080, 1920, 48000, 'image/jpeg', false),
('still-water-thumb', 'still-water', 'thumbnail', 'public', '/wallpapers/still-water.jpg', 400, 711, 12000, 'image/jpeg', true),
('still-water-prev', 'still-water', 'preview', 'public', '/wallpapers/still-water.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('still-water-orig', 'still-water', 'original', 'protected', '/wallpapers/still-water.jpg', 1080, 1920, 48000, 'image/jpeg', false),
('afterglow-run-thumb', 'afterglow-run', 'thumbnail', 'public', '/wallpapers/afterglow-run.jpg', 400, 711, 12000, 'image/jpeg', true),
('afterglow-run-prev', 'afterglow-run', 'preview', 'public', '/wallpapers/afterglow-run.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('afterglow-run-orig', 'afterglow-run', 'original', 'protected', '/wallpapers/afterglow-run.jpg', 1080, 1920, 48000, 'image/jpeg', false),
('night-circuit-thumb', 'night-circuit', 'thumbnail', 'public', '/wallpapers/night-circuit.jpg', 400, 711, 12000, 'image/jpeg', true),
('night-circuit-prev', 'night-circuit', 'preview', 'public', '/wallpapers/night-circuit.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('night-circuit-orig', 'night-circuit', 'original', 'protected', '/wallpapers/night-circuit.jpg', 1080, 1920, 48000, 'image/jpeg', false),
('after-rain-sky-thumb', 'after-rain-sky', 'thumbnail', 'public', '/wallpapers/after-rain-sky.jpg', 400, 711, 12000, 'image/jpeg', true),
('after-rain-sky-prev', 'after-rain-sky', 'preview', 'public', '/wallpapers/after-rain-sky.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('after-rain-sky-orig', 'after-rain-sky', 'original', 'protected', '/wallpapers/after-rain-sky.jpg', 1080, 1920, 48000, 'image/jpeg', false),
('school-route-thumb', 'school-route', 'thumbnail', 'public', '/wallpapers/school-route.jpg', 400, 711, 12000, 'image/jpeg', true),
('school-route-prev', 'school-route', 'preview', 'public', '/wallpapers/school-route.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('school-route-orig', 'school-route', 'original', 'protected', '/wallpapers/school-route.jpg', 1080, 1920, 48000, 'image/jpeg', false),
('silent-satellite-thumb', 'silent-satellite', 'thumbnail', 'public', '/wallpapers/silent-satellite.jpg', 400, 711, 12000, 'image/jpeg', true),
('silent-satellite-prev', 'silent-satellite', 'preview', 'public', '/wallpapers/silent-satellite.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('silent-satellite-orig', 'silent-satellite', 'original', 'protected', '/wallpapers/silent-satellite.jpg', 1080, 1920, 48000, 'image/jpeg', false),
('kepler-dust-thumb', 'kepler-dust', 'thumbnail', 'public', '/wallpapers/kepler-dust.jpg', 400, 711, 12000, 'image/jpeg', true),
('kepler-dust-prev', 'kepler-dust', 'preview', 'public', '/wallpapers/kepler-dust.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('kepler-dust-orig', 'kepler-dust', 'original', 'protected', '/wallpapers/kepler-dust.jpg', 1080, 1920, 48000, 'image/jpeg', false),
('low-light-thumb', 'low-light', 'thumbnail', 'public', '/wallpapers/low-light.jpg', 400, 711, 12000, 'image/jpeg', true),
('low-light-prev', 'low-light', 'preview', 'public', '/wallpapers/low-light.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('low-light-orig', 'low-light', 'original', 'protected', '/wallpapers/low-light.jpg', 1080, 1920, 48000, 'image/jpeg', false),
('charcoal-fold-thumb', 'charcoal-fold', 'thumbnail', 'public', '/wallpapers/charcoal-fold.jpg', 400, 711, 12000, 'image/jpeg', true),
('charcoal-fold-prev', 'charcoal-fold', 'preview', 'public', '/wallpapers/charcoal-fold.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('charcoal-fold-orig', 'charcoal-fold', 'original', 'protected', '/wallpapers/charcoal-fold.jpg', 1080, 1920, 48000, 'image/jpeg', false),
('overlap-two-thumb', 'overlap-two', 'thumbnail', 'public', '/wallpapers/overlap-two.jpg', 400, 711, 12000, 'image/jpeg', true),
('overlap-two-prev', 'overlap-two', 'preview', 'public', '/wallpapers/overlap-two.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('overlap-two-orig', 'overlap-two', 'original', 'protected', '/wallpapers/overlap-two.jpg', 1080, 1920, 48000, 'image/jpeg', false),
('lattice-soft-thumb', 'lattice-soft', 'thumbnail', 'public', '/wallpapers/lattice-soft.jpg', 400, 711, 12000, 'image/jpeg', true),
('lattice-soft-prev', 'lattice-soft', 'preview', 'public', '/wallpapers/lattice-soft.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('lattice-soft-orig', 'lattice-soft', 'original', 'protected', '/wallpapers/lattice-soft.jpg', 1080, 1920, 48000, 'image/jpeg', false),
('begin-again-thumb', 'begin-again', 'thumbnail', 'public', '/wallpapers/begin-again.jpg', 400, 711, 12000, 'image/jpeg', true),
('begin-again-prev', 'begin-again', 'preview', 'public', '/wallpapers/begin-again.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('begin-again-orig', 'begin-again', 'original', 'protected', '/wallpapers/begin-again.jpg', 1080, 1920, 48000, 'image/jpeg', false),
('make-room-thumb', 'make-room', 'thumbnail', 'public', '/wallpapers/make-room.jpg', 400, 711, 12000, 'image/jpeg', true),
('make-room-prev', 'make-room', 'preview', 'public', '/wallpapers/make-room.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('make-room-orig', 'make-room', 'original', 'protected', '/wallpapers/make-room.jpg', 1080, 1920, 48000, 'image/jpeg', false),
('be-still-thumb', 'be-still', 'thumbnail', 'public', '/wallpapers/be-still.jpg', 400, 711, 12000, 'image/jpeg', true),
('be-still-prev', 'be-still', 'preview', 'public', '/wallpapers/be-still.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('be-still-orig', 'be-still', 'original', 'protected', '/wallpapers/be-still.jpg', 1080, 1920, 48000, 'image/jpeg', false),
('let-there-be-light-thumb', 'let-there-be-light', 'thumbnail', 'public', '/wallpapers/let-there-be-light.jpg', 400, 711, 12000, 'image/jpeg', true),
('let-there-be-light-prev', 'let-there-be-light', 'preview', 'public', '/wallpapers/let-there-be-light.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('let-there-be-light-orig', 'let-there-be-light', 'original', 'protected', '/wallpapers/let-there-be-light.jpg', 1080, 1920, 48000, 'image/jpeg', false),
('two-points-thumb', 'two-points', 'thumbnail', 'public', '/wallpapers/two-points.jpg', 400, 711, 12000, 'image/jpeg', true),
('two-points-prev', 'two-points', 'preview', 'public', '/wallpapers/two-points.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('two-points-orig', 'two-points', 'original', 'protected', '/wallpapers/two-points.jpg', 1080, 1920, 48000, 'image/jpeg', false),
('held-thumb', 'held', 'thumbnail', 'public', '/wallpapers/held.jpg', 400, 711, 12000, 'image/jpeg', true),
('held-prev', 'held', 'preview', 'public', '/wallpapers/held.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('held-orig', 'held', 'original', 'protected', '/wallpapers/held.jpg', 1080, 1920, 48000, 'image/jpeg', false),
('late-grid-thumb', 'late-grid', 'thumbnail', 'public', '/wallpapers/late-grid.jpg', 400, 711, 12000, 'image/jpeg', true),
('late-grid-prev', 'late-grid', 'preview', 'public', '/wallpapers/late-grid.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('late-grid-orig', 'late-grid', 'original', 'protected', '/wallpapers/late-grid.jpg', 1080, 1920, 48000, 'image/jpeg', false),
('harbour-hour-thumb', 'harbour-hour', 'thumbnail', 'public', '/wallpapers/harbour-hour.jpg', 400, 711, 12000, 'image/jpeg', true),
('harbour-hour-prev', 'harbour-hour', 'preview', 'public', '/wallpapers/harbour-hour.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('harbour-hour-orig', 'harbour-hour', 'original', 'protected', '/wallpapers/harbour-hour.jpg', 1080, 1920, 48000, 'image/jpeg', false),
('crane-hour-thumb', 'crane-hour', 'thumbnail', 'public', '/wallpapers/crane-hour.jpg', 400, 711, 12000, 'image/jpeg', true),
('crane-hour-prev', 'crane-hour', 'preview', 'public', '/wallpapers/crane-hour.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('crane-hour-orig', 'crane-hour', 'original', 'protected', '/wallpapers/crane-hour.jpg', 1080, 1920, 48000, 'image/jpeg', false),
('deep-hold-thumb', 'deep-hold', 'thumbnail', 'public', '/wallpapers/deep-hold.jpg', 400, 711, 12000, 'image/jpeg', true),
('deep-hold-prev', 'deep-hold', 'preview', 'public', '/wallpapers/deep-hold.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('deep-hold-orig', 'deep-hold', 'original', 'protected', '/wallpapers/deep-hold.jpg', 1080, 1920, 48000, 'image/jpeg', false),
('sepia-room-thumb', 'sepia-room', 'thumbnail', 'public', '/wallpapers/sepia-room.jpg', 400, 711, 12000, 'image/jpeg', true),
('sepia-room-prev', 'sepia-room', 'preview', 'public', '/wallpapers/sepia-room.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('sepia-room-orig', 'sepia-room', 'original', 'protected', '/wallpapers/sepia-room.jpg', 1080, 1920, 48000, 'image/jpeg', false),
('old-letter-thumb', 'old-letter', 'thumbnail', 'public', '/wallpapers/old-letter.jpg', 400, 711, 12000, 'image/jpeg', true),
('old-letter-prev', 'old-letter', 'preview', 'public', '/wallpapers/old-letter.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('old-letter-orig', 'old-letter', 'original', 'protected', '/wallpapers/old-letter.jpg', 1080, 1920, 48000, 'image/jpeg', false),
('true-black-thumb', 'true-black', 'thumbnail', 'public', '/wallpapers/true-black.jpg', 400, 711, 12000, 'image/jpeg', true),
('true-black-prev', 'true-black', 'preview', 'public', '/wallpapers/true-black.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('true-black-orig', 'true-black', 'original', 'protected', '/wallpapers/true-black.jpg', 1080, 1920, 48000, 'image/jpeg', false),
('thin-cross-thumb', 'thin-cross', 'thumbnail', 'public', '/wallpapers/thin-cross.jpg', 400, 711, 12000, 'image/jpeg', true),
('thin-cross-prev', 'thin-cross', 'preview', 'public', '/wallpapers/thin-cross.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('thin-cross-orig', 'thin-cross', 'original', 'protected', '/wallpapers/thin-cross.jpg', 1080, 1920, 48000, 'image/jpeg', false),
('soft-lock-thumb', 'soft-lock', 'thumbnail', 'public', '/wallpapers/soft-lock.jpg', 400, 711, 12000, 'image/jpeg', true),
('soft-lock-prev', 'soft-lock', 'preview', 'public', '/wallpapers/soft-lock.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('soft-lock-orig', 'soft-lock', 'original', 'protected', '/wallpapers/soft-lock.jpg', 1080, 1920, 48000, 'image/jpeg', false),
('lock-dune-thumb', 'lock-dune', 'thumbnail', 'public', '/wallpapers/lock-dune.jpg', 400, 711, 12000, 'image/jpeg', true),
('lock-dune-prev', 'lock-dune', 'preview', 'public', '/wallpapers/lock-dune.jpg', 1080, 1920, 48000, 'image/jpeg', true),
('lock-dune-orig', 'lock-dune', 'original', 'protected', '/wallpapers/lock-dune.jpg', 1080, 1920, 48000, 'image/jpeg', false)
on conflict (id) do nothing;

insert into wallpaper_tags (wallpaper_id, tag_id)
values
('quiet-orbit', 'tag-minimal'),
('quiet-orbit', 'tag-circle'),
('quiet-orbit', 'tag-calm'),
('one-line', 'tag-minimal'),
('one-line', 'tag-line'),
('paper-moon', 'tag-aesthetic'),
('paper-moon', 'tag-moon'),
('paper-moon', 'tag-film'),
('film-dust', 'tag-aesthetic'),
('film-dust', 'tag-grain'),
('film-dust', 'tag-rose'),
('ridge-line', 'tag-nature'),
('ridge-line', 'tag-mountains'),
('ridge-line', 'tag-dusk'),
('still-water', 'tag-nature'),
('still-water', 'tag-water'),
('afterglow-run', 'tag-cars'),
('afterglow-run', 'tag-road'),
('afterglow-run', 'tag-sunset'),
('night-circuit', 'tag-cars'),
('night-circuit', 'tag-night'),
('night-circuit', 'tag-bokeh'),
('after-rain-sky', 'tag-anime'),
('after-rain-sky', 'tag-sky'),
('after-rain-sky', 'tag-dusk'),
('school-route', 'tag-anime'),
('school-route', 'tag-evening'),
('silent-satellite', 'tag-space'),
('silent-satellite', 'tag-moon'),
('silent-satellite', 'tag-stars'),
('kepler-dust', 'tag-space'),
('kepler-dust', 'tag-nebula'),
('low-light', 'tag-dark'),
('low-light', 'tag-black'),
('low-light', 'tag-seam'),
('charcoal-fold', 'tag-dark'),
('charcoal-fold', 'tag-grey'),
('overlap-two', 'tag-abstract'),
('overlap-two', 'tag-circle'),
('lattice-soft', 'tag-abstract'),
('lattice-soft', 'tag-grid'),
('begin-again', 'tag-type'),
('begin-again', 'tag-calm'),
('make-room', 'tag-type'),
('be-still', 'tag-verse'),
('be-still', 'tag-psalm'),
('let-there-be-light', 'tag-verse'),
('let-there-be-light', 'tag-genesis'),
('two-points', 'tag-love'),
('two-points', 'tag-minimal'),
('held', 'tag-love'),
('held', 'tag-dusk'),
('late-grid', 'tag-city'),
('late-grid', 'tag-night'),
('harbour-hour', 'tag-city'),
('harbour-hour', 'tag-blue hour'),
('crane-hour', 'tag-animals'),
('crane-hour', 'tag-bird'),
('deep-hold', 'tag-animals'),
('deep-hold', 'tag-ocean'),
('sepia-room', 'tag-vintage'),
('sepia-room', 'tag-sepia'),
('old-letter', 'tag-vintage'),
('old-letter', 'tag-paper'),
('true-black', 'tag-amoled'),
('true-black', 'tag-black'),
('thin-cross', 'tag-amoled'),
('thin-cross', 'tag-geometry'),
('soft-lock', 'tag-iphone'),
('soft-lock', 'tag-lockscreen'),
('lock-dune', 'tag-iphone'),
('lock-dune', 'tag-dune')
on conflict do nothing;

insert into featured_wallpapers (id, slot, wallpaper_id, starts_at, ends_at, priority)
values
('feat-paper-moon', 'editors_choice', 'paper-moon', now() - interval '1 day', now() + interval '365 days', 10),
('feat-ridge-line', 'wotd', 'ridge-line', now() - interval '1 day', now() + interval '365 days', 9),
('feat-after-rain-sky', 'editors_choice', 'after-rain-sky', now() - interval '1 day', now() + interval '365 days', 8),
('feat-silent-satellite', 'editors_choice', 'silent-satellite', now() - interval '1 day', now() + interval '365 days', 7),
('feat-overlap-two', 'editors_choice', 'overlap-two', now() - interval '1 day', now() + interval '365 days', 6),
('feat-be-still', 'editors_choice', 'be-still', now() - interval '1 day', now() + interval '365 days', 5),
('feat-late-grid', 'editors_choice', 'late-grid', now() - interval '1 day', now() + interval '365 days', 4),
('feat-true-black', 'editors_choice', 'true-black', now() - interval '1 day', now() + interval '365 days', 3),
('feat-thin-cross', 'premium_spotlight', 'thin-cross', now() - interval '1 day', now() + interval '365 days', 2),
('feat-lock-dune', 'premium_spotlight', 'lock-dune', now() - interval '1 day', now() + interval '365 days', 1)
on conflict (id) do nothing;

insert into collections (id, slug, name, description, cover_url, is_visible)
values
('col-amoled', 'best-amoled', 'Best AMOLED Wallpapers', 'True black, built for OLED.', '/wallpapers/true-black.jpg', true),
('col-minimal-iphone', 'minimal-iphone', 'Minimal iPhone Wallpapers', 'Quiet compositions for a tall screen.', '/wallpapers/soft-lock.jpg', true),
('col-dark', 'dark-wallpapers', 'Dark Wallpapers', 'Low light, no glare.', '/wallpapers/low-light.jpg', true)
on conflict (id) do nothing;

insert into collection_wallpapers (collection_id, wallpaper_id, sort_order)
values
('col-amoled', 'true-black', 0),
('col-amoled', 'thin-cross', 1),
('col-amoled', 'low-light', 2),
('col-amoled', 'quiet-orbit', 3),
('col-minimal-iphone', 'soft-lock', 0),
('col-minimal-iphone', 'quiet-orbit', 1),
('col-minimal-iphone', 'one-line', 2),
('col-minimal-iphone', 'lock-dune', 3),
('col-dark', 'low-light', 0),
('col-dark', 'charcoal-fold', 1),
('col-dark', 'true-black', 2),
('col-dark', 'silent-satellite', 3)
on conflict do nothing;
