/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AppRouteImport } from './routes/app'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ApiStudioOriginalRouteImport } from './routes/api/studio-original'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCreatorsRouteImport } from './routes/app/creators'
import { Route as AppDownloadsRouteImport } from './routes/app/downloads'
import { Route as AppExploreRouteImport } from './routes/app/explore'
import { Route as AppFavoritesRouteImport } from './routes/app/favorites'
import { Route as AppNotificationsRouteImport } from './routes/app/notifications'
import { Route as AppPremiumRouteImport } from './routes/app/premium'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppTasteRouteImport } from './routes/app/taste'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as CollectionSlugRouteImport } from './routes/collection.$slug'
import { Route as CreatorSlugRouteImport } from './routes/creator.$slug'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as MediaSplatRouteImport } from './routes/media.$'
import { Route as OpsIndexRouteImport } from './routes/ops/index'
import { Route as OpsCreatorsRouteImport } from './routes/ops/creators'
import { Route as OpsReportsRouteImport } from './routes/ops/reports'
import { Route as OpsSettingsRouteImport } from './routes/ops/settings'
import { Route as OpsUsersRouteImport } from './routes/ops/users'
import { Route as OpsWallpapersRouteImport } from './routes/ops/wallpapers'
import { Route as PairSlugRouteImport } from './routes/pair.$slug'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as StudioApplyRouteImport } from './routes/studio/apply'
import { Route as StudioSubmitRouteImport } from './routes/studio/submit'
import { Route as WallpaperIdRouteImport } from './routes/wallpaper.$id'
import { Route as WallpapersIndexRouteImport } from './routes/wallpapers.index'
import { Route as WallpapersSlugRouteImport } from './routes/wallpapers.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMediaIdRouteImport } from './routes/api/media.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudioOriginalRoute = ApiStudioOriginalRouteImport.update({
  id: '/api/studio-original',
  path: '/api/studio-original',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCreatorsRoute = AppCreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => AppRoute,
} as any)
const AppDownloadsRoute = AppDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPremiumRoute = AppPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppTasteRoute = AppTasteRouteImport.update({
  id: '/taste',
  path: '/taste',
  getParentRoute: () => AppRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionSlugRoute = CollectionSlugRouteImport.update({
  id: '/collection/$slug',
  path: '/collection/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorSlugRoute = CreatorSlugRouteImport.update({
  id: '/creator/$slug',
  path: '/creator/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaSplatRoute = MediaSplatRouteImport.update({
  id: '/media/$',
  path: '/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRoute,
} as any)
const OpsCreatorsRoute = OpsCreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => OpsRoute,
} as any)
const OpsReportsRoute = OpsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => OpsRoute,
} as any)
const OpsSettingsRoute = OpsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OpsRoute,
} as any)
const OpsUsersRoute = OpsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => OpsRoute,
} as any)
const OpsWallpapersRoute = OpsWallpapersRouteImport.update({
  id: '/wallpapers',
  path: '/wallpapers',
  getParentRoute: () => OpsRoute,
} as any)
const PairSlugRoute = PairSlugRouteImport.update({
  id: '/pair/$slug',
  path: '/pair/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioApplyRoute = StudioApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => StudioRoute,
} as any)
const StudioSubmitRoute = StudioSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => StudioRoute,
} as any)
const WallpaperIdRoute = WallpaperIdRouteImport.update({
  id: '/wallpaper/$id',
  path: '/wallpaper/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WallpapersIndexRoute = WallpapersIndexRouteImport.update({
  id: '/wallpapers/',
  path: '/wallpapers/',
  getParentRoute: () => rootRouteImport,
} as any)
const WallpapersSlugRoute = WallpapersSlugRouteImport.update({
  id: '/wallpapers/$slug',
  path: '/wallpapers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaIdRoute = ApiMediaIdRouteImport.update({
  id: '/api/media/$id',
  path: '/api/media/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/app': typeof AppRouteWithChildren
  '/creators': typeof CreatorsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/ops': typeof OpsRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRouteWithChildren
  '/api/studio-original': typeof ApiStudioOriginalRoute
  '/app/creators': typeof AppCreatorsRoute
  '/app/downloads': typeof AppDownloadsRoute
  '/app/explore': typeof AppExploreRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/profile': typeof AppProfileRoute
  '/app/taste': typeof AppTasteRoute
  '/category/$slug': typeof CategorySlugRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/creator/$slug': typeof CreatorSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/media/$': typeof MediaSplatRoute
  '/ops/creators': typeof OpsCreatorsRoute
  '/ops/reports': typeof OpsReportsRoute
  '/ops/settings': typeof OpsSettingsRoute
  '/ops/users': typeof OpsUsersRoute
  '/ops/wallpapers': typeof OpsWallpapersRoute
  '/pair/$slug': typeof PairSlugRoute
  '/studio/apply': typeof StudioApplyRoute
  '/studio/submit': typeof StudioSubmitRoute
  '/wallpaper/$id': typeof WallpaperIdRoute
  '/wallpapers/$slug': typeof WallpapersSlugRoute
  '/app/': typeof AppIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/wallpapers/': typeof WallpapersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$id': typeof ApiMediaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/creators': typeof CreatorsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/studio-original': typeof ApiStudioOriginalRoute
  '/app/creators': typeof AppCreatorsRoute
  '/app/downloads': typeof AppDownloadsRoute
  '/app/explore': typeof AppExploreRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/profile': typeof AppProfileRoute
  '/app/taste': typeof AppTasteRoute
  '/category/$slug': typeof CategorySlugRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/creator/$slug': typeof CreatorSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/media/$': typeof MediaSplatRoute
  '/ops/creators': typeof OpsCreatorsRoute
  '/ops/reports': typeof OpsReportsRoute
  '/ops/settings': typeof OpsSettingsRoute
  '/ops/users': typeof OpsUsersRoute
  '/ops/wallpapers': typeof OpsWallpapersRoute
  '/pair/$slug': typeof PairSlugRoute
  '/studio/apply': typeof StudioApplyRoute
  '/studio/submit': typeof StudioSubmitRoute
  '/wallpaper/$id': typeof WallpaperIdRoute
  '/wallpapers/$slug': typeof WallpapersSlugRoute
  '/app': typeof AppIndexRoute
  '/ops': typeof OpsIndexRoute
  '/studio': typeof StudioIndexRoute
  '/wallpapers': typeof WallpapersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$id': typeof ApiMediaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/app': typeof AppRouteWithChildren
  '/creators': typeof CreatorsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/ops': typeof OpsRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRouteWithChildren
  '/api/studio-original': typeof ApiStudioOriginalRoute
  '/app/creators': typeof AppCreatorsRoute
  '/app/downloads': typeof AppDownloadsRoute
  '/app/explore': typeof AppExploreRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/premium': typeof AppPremiumRoute
  '/app/profile': typeof AppProfileRoute
  '/app/taste': typeof AppTasteRoute
  '/category/$slug': typeof CategorySlugRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/creator/$slug': typeof CreatorSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/media/$': typeof MediaSplatRoute
  '/ops/creators': typeof OpsCreatorsRoute
  '/ops/reports': typeof OpsReportsRoute
  '/ops/settings': typeof OpsSettingsRoute
  '/ops/users': typeof OpsUsersRoute
  '/ops/wallpapers': typeof OpsWallpapersRoute
  '/pair/$slug': typeof PairSlugRoute
  '/studio/apply': typeof StudioApplyRoute
  '/studio/submit': typeof StudioSubmitRoute
  '/wallpaper/$id': typeof WallpaperIdRoute
  '/wallpapers/$slug': typeof WallpapersSlugRoute
  '/app/': typeof AppIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/wallpapers/': typeof WallpapersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$id': typeof ApiMediaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/app'
    | '/creators'
    | '/login'
    | '/onboarding'
    | '/ops'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/studio'
    | '/api/studio-original'
    | '/app/creators'
    | '/app/downloads'
    | '/app/explore'
    | '/app/favorites'
    | '/app/notifications'
    | '/app/premium'
    | '/app/profile'
    | '/app/taste'
    | '/category/$slug'
    | '/collection/$slug'
    | '/creator/$slug'
    | '/legal/$slug'
    | '/media/$'
    | '/ops/creators'
    | '/ops/reports'
    | '/ops/settings'
    | '/ops/users'
    | '/ops/wallpapers'
    | '/pair/$slug'
    | '/studio/apply'
    | '/studio/submit'
    | '/wallpaper/$id'
    | '/wallpapers/$slug'
    | '/app/'
    | '/ops/'
    | '/studio/'
    | '/wallpapers/'
    | '/api/auth/$'
    | '/api/media/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/creators'
    | '/login'
    | '/onboarding'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/studio-original'
    | '/app/creators'
    | '/app/downloads'
    | '/app/explore'
    | '/app/favorites'
    | '/app/notifications'
    | '/app/premium'
    | '/app/profile'
    | '/app/taste'
    | '/category/$slug'
    | '/collection/$slug'
    | '/creator/$slug'
    | '/legal/$slug'
    | '/media/$'
    | '/ops/creators'
    | '/ops/reports'
    | '/ops/settings'
    | '/ops/users'
    | '/ops/wallpapers'
    | '/pair/$slug'
    | '/studio/apply'
    | '/studio/submit'
    | '/wallpaper/$id'
    | '/wallpapers/$slug'
    | '/app'
    | '/ops'
    | '/studio'
    | '/wallpapers'
    | '/api/auth/$'
    | '/api/media/$id'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/app'
    | '/creators'
    | '/login'
    | '/onboarding'
    | '/ops'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/studio'
    | '/api/studio-original'
    | '/app/creators'
    | '/app/downloads'
    | '/app/explore'
    | '/app/favorites'
    | '/app/notifications'
    | '/app/premium'
    | '/app/profile'
    | '/app/taste'
    | '/category/$slug'
    | '/collection/$slug'
    | '/creator/$slug'
    | '/legal/$slug'
    | '/media/$'
    | '/ops/creators'
    | '/ops/reports'
    | '/ops/settings'
    | '/ops/users'
    | '/ops/wallpapers'
    | '/pair/$slug'
    | '/studio/apply'
    | '/studio/submit'
    | '/wallpaper/$id'
    | '/wallpapers/$slug'
    | '/app/'
    | '/ops/'
    | '/studio/'
    | '/wallpapers/'
    | '/api/auth/$'
    | '/api/media/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  CreatorsRoute: typeof CreatorsRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OpsRoute: typeof OpsRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioRoute: typeof StudioRouteWithChildren
  ApiStudioOriginalRoute: typeof ApiStudioOriginalRoute
  CategorySlugRoute: typeof CategorySlugRoute
  CollectionSlugRoute: typeof CollectionSlugRoute
  CreatorSlugRoute: typeof CreatorSlugRoute
  LegalSlugRoute: typeof LegalSlugRoute
  MediaSplatRoute: typeof MediaSplatRoute
  PairSlugRoute: typeof PairSlugRoute
  WallpaperIdRoute: typeof WallpaperIdRoute
  WallpapersSlugRoute: typeof WallpapersSlugRoute
  WallpapersIndexRoute: typeof WallpapersIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMediaIdRoute: typeof ApiMediaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/studio-original': {
      id: '/api/studio-original'
      path: '/api/studio-original'
      fullPath: '/api/studio-original'
      preLoaderRoute: typeof ApiStudioOriginalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/creators': {
      id: '/app/creators'
      path: '/creators'
      fullPath: '/app/creators'
      preLoaderRoute: typeof AppCreatorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/downloads': {
      id: '/app/downloads'
      path: '/downloads'
      fullPath: '/app/downloads'
      preLoaderRoute: typeof AppDownloadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/explore': {
      id: '/app/explore'
      path: '/explore'
      fullPath: '/app/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/favorites': {
      id: '/app/favorites'
      path: '/favorites'
      fullPath: '/app/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/premium': {
      id: '/app/premium'
      path: '/premium'
      fullPath: '/app/premium'
      preLoaderRoute: typeof AppPremiumRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/taste': {
      id: '/app/taste'
      path: '/taste'
      fullPath: '/app/taste'
      preLoaderRoute: typeof AppTasteRouteImport
      parentRoute: typeof AppRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$slug': {
      id: '/collection/$slug'
      path: '/collection/$slug'
      fullPath: '/collection/$slug'
      preLoaderRoute: typeof CollectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/$slug': {
      id: '/creator/$slug'
      path: '/creator/$slug'
      fullPath: '/creator/$slug'
      preLoaderRoute: typeof CreatorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$': {
      id: '/media/$'
      path: '/media/$'
      fullPath: '/media/$'
      preLoaderRoute: typeof MediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/': {
      id: '/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/creators': {
      id: '/ops/creators'
      path: '/creators'
      fullPath: '/ops/creators'
      preLoaderRoute: typeof OpsCreatorsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/reports': {
      id: '/ops/reports'
      path: '/reports'
      fullPath: '/ops/reports'
      preLoaderRoute: typeof OpsReportsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/settings': {
      id: '/ops/settings'
      path: '/settings'
      fullPath: '/ops/settings'
      preLoaderRoute: typeof OpsSettingsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/users': {
      id: '/ops/users'
      path: '/users'
      fullPath: '/ops/users'
      preLoaderRoute: typeof OpsUsersRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/wallpapers': {
      id: '/ops/wallpapers'
      path: '/wallpapers'
      fullPath: '/ops/wallpapers'
      preLoaderRoute: typeof OpsWallpapersRouteImport
      parentRoute: typeof OpsRoute
    }
    '/pair/$slug': {
      id: '/pair/$slug'
      path: '/pair/$slug'
      fullPath: '/pair/$slug'
      preLoaderRoute: typeof PairSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/apply': {
      id: '/studio/apply'
      path: '/apply'
      fullPath: '/studio/apply'
      preLoaderRoute: typeof StudioApplyRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/submit': {
      id: '/studio/submit'
      path: '/submit'
      fullPath: '/studio/submit'
      preLoaderRoute: typeof StudioSubmitRouteImport
      parentRoute: typeof StudioRoute
    }
    '/wallpaper/$id': {
      id: '/wallpaper/$id'
      path: '/wallpaper/$id'
      fullPath: '/wallpaper/$id'
      preLoaderRoute: typeof WallpaperIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallpapers/': {
      id: '/wallpapers/'
      path: '/wallpapers'
      fullPath: '/wallpapers/'
      preLoaderRoute: typeof WallpapersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallpapers/$slug': {
      id: '/wallpapers/$slug'
      path: '/wallpapers/$slug'
      fullPath: '/wallpapers/$slug'
      preLoaderRoute: typeof WallpapersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$id': {
      id: '/api/media/$id'
      path: '/api/media/$id'
      fullPath: '/api/media/$id'
      preLoaderRoute: typeof ApiMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCreatorsRoute: typeof AppCreatorsRoute
  AppDownloadsRoute: typeof AppDownloadsRoute
  AppExploreRoute: typeof AppExploreRoute
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPremiumRoute: typeof AppPremiumRoute
  AppProfileRoute: typeof AppProfileRoute
  AppTasteRoute: typeof AppTasteRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCreatorsRoute: AppCreatorsRoute,
  AppDownloadsRoute: AppDownloadsRoute,
  AppExploreRoute: AppExploreRoute,
  AppFavoritesRoute: AppFavoritesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPremiumRoute: AppPremiumRoute,
  AppProfileRoute: AppProfileRoute,
  AppTasteRoute: AppTasteRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OpsRouteChildren {
  OpsCreatorsRoute: typeof OpsCreatorsRoute
  OpsReportsRoute: typeof OpsReportsRoute
  OpsSettingsRoute: typeof OpsSettingsRoute
  OpsUsersRoute: typeof OpsUsersRoute
  OpsWallpapersRoute: typeof OpsWallpapersRoute
  OpsIndexRoute: typeof OpsIndexRoute
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsCreatorsRoute: OpsCreatorsRoute,
  OpsReportsRoute: OpsReportsRoute,
  OpsSettingsRoute: OpsSettingsRoute,
  OpsUsersRoute: OpsUsersRoute,
  OpsWallpapersRoute: OpsWallpapersRoute,
  OpsIndexRoute: OpsIndexRoute,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

interface StudioRouteChildren {
  StudioApplyRoute: typeof StudioApplyRoute
  StudioSubmitRoute: typeof StudioSubmitRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioApplyRoute: StudioApplyRoute,
  StudioSubmitRoute: StudioSubmitRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  CreatorsRoute: CreatorsRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OpsRoute: OpsRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioRoute: StudioRouteWithChildren,
  ApiStudioOriginalRoute: ApiStudioOriginalRoute,
  CategorySlugRoute: CategorySlugRoute,
  CollectionSlugRoute: CollectionSlugRoute,
  CreatorSlugRoute: CreatorSlugRoute,
  LegalSlugRoute: LegalSlugRoute,
  MediaSplatRoute: MediaSplatRoute,
  PairSlugRoute: PairSlugRoute,
  WallpaperIdRoute: WallpaperIdRoute,
  WallpapersSlugRoute: WallpapersSlugRoute,
  WallpapersIndexRoute: WallpapersIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMediaIdRoute: ApiMediaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
